services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas